////
 *   RapCAD - Rapid prototyping CAD IDE (www.rapcad.org)
 *   Copyright (C) 2010  Giles Bathgate
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
////

Compiling
---------

The following instructions will allow you to compile RapCAD from source on
various platforms.

Linux
~~~~~

Prerequisites
^^^^^^^^^^^^^

The source code is hosted in a git repository so you might want to install git first

git
+++
[source,shell]
-----------------------------
sudo apt-get install git-core
-----------------------------


Dependencies
++++++++++++
[source,shell]
---------------------------------------------------------------------------------
sudo apt-get install g++ libcgal-dev libqt5opengl5-dev bison flex libreadline-dev
---------------------------------------------------------------------------------

RapCAD
++++++
[source,shell]
-------------------------------------
git clone git://git.rapcad.org/rapcad

cd rapcad &&
qmake &&
make
-------------------------------------

Windows
~~~~~~~

Qt (MinGW)
^^^^^^^^^^

* Download Qt installer
http://download.qt.io/official_releases/qt/5.5/5.5.1/qt-opensource-windows-x86-mingw492-5.5.1.exe[qt-opensource-windows-x86-mingw492-5.5.1.exe]
* Install to default location +C:\Qt\Qt5.5.1\+

CMake
^^^^^

* Download CMake installer
https://cmake.org/files/v3.4/cmake-3.4.0-rc2-win32-x86.exe[cmake-3.4.0-rc2-win32-x86.exe]
* Check the 'Add cmake to the system path for the current user' checkbox
* Install to default location +C:\Program Files\CMake 3.4+

Boost
^^^^^

* Download Boost source
http://downloads.sourceforge.net/project/boost/boost/1.59.0/boost_1.59.0.7z[boost_1.59.0.7z]
* Extract all to +C:\+ (sources will end up in +C:\boost_1_59_0\+ )
* Use the QT Development Command Prompt +
+Start->Program Files->Qt by Nokia v5.5.1 (MinGW OpenSource)->QT 5.5.1 Command Prompt+
[source,bat]
-------------------------
cd "C:\boost_1_55_0"
bootstrap.bat mingw
.\b2 toolset=gcc variant=release --with-thread --with-system
-------------------------

CGAL
^^^^

* Download CGAL installer
https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-4.7/CGAL-4.7-Setup.exe[CGAL-4.7-Setup.exe]


NOTE: CGAL-4.7-Setup.exe is not a binary distribution, just an installer that installs the
source.

* No need for 'CGAL Examples and Demos'
* Make sure 'mpfr and gmp precompiled libs' is checked
* Install to +C:\CGAL-4.7\+
* Make sure 'CGAL_DIR' environment checked.
* Use the QT Development Command Prompt +
+Start->Program Files->Qt by Nokia v5.5.1 (MinGW OpenSource)->QT 5.5.1 Command Prompt+
[source,bat]
-------------------------------
set PATH=%PATH%;"C:\Program Files\CMake 3.4\bin"
set BOOST_ROOT=C:\boost_1_59_0
cd "C:\CGAL-4.7"
cmake -G"MinGW Makefiles" .
mingw32-make
-------------------------------

macOS 10.12.2 (Sierra)
~~~~~~~~~~~~~~~

Xcode (8.2.1)
^^^^^^^^^

Register with Apple and download
link:https://developer.apple.com/xcode/[Xcode].
Install the package accepting the default options.

MacPorts
^^^^^^^^

Download the
link:https://github.com/macports/macports-base/releases/download/v2.3.5/MacPorts-2.3.5-10.12-Sierra.pkg[MacPorts Installer].
Install the package accepting the default options.

Dependencies
++++++++++++
[source,shell]
-------------------------------------------------------------
xcode-license --install
sudo port install qt5 cgal
sudo port install cgal +qt5
-------------------------------------------------------------

RapCAD
++++++
[source,shell]
-------------------------
qmake CONFIG+=official
make
cp -R /opt/local/lib/Resources/qt_menu.nib rapcad.app/Contents/Resources/
macdeployqt rapcad.app -dmg
hdiutil internet-enable -yes rapcad.dmg
-------------------------

If qmake doesn't work initially, you'll need to manually add qmake to your PATH, so run
[source,shell]
-------------------------
sudo ln -s /opt/local/libexec/qt5/bin/qmake /opt/local/bin/qmake
-------------------------


